package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	TOKEN_REQUEST,TOKEN_REPLY , BACKUP , PING, PONG
	,SUS , REMOVED_NODE, SUS_RESPONSE , TELL_VIEW, ASK_DELETE, TELL_DELETE, ASK_VIEW

}
